model_name_or_path: Rostlab/prot_xlnet
tokenizer_name: Rostlab/prot_xlnet
train_file: /workspace/lm/prottrans_all_oas_human_VH_seqs_ALL_cutoff90_train.txt
validation_file: /workspace/lm/prottrans_all_oas_human_VH_seqs_ALL_cutoff90_val.txt
preprocessing_num_workers: 64
num_train_epochs: 20
gradient_accumulation_steps: 4
line_by_line: True
per_device_train_batch_size: 8
per_device_eval_batch_size: 8
learning_rate: 5.0e-5
logging_steps: 5000
save_steps: 5000
logging_first_step: True
evaluation_strategy: epoch
do_train: True
do_eval: True
output_dir: /workspace/lm/output
